spring:
  datasource:
    url: "jdbc:mysql://192.168.72.128:3306/book_talk?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}

  servlet:
    encoding:
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  redis:
    host: 192.168.72.128
    port: 6379
    password: ${REDIS_PASSWORD}   # 如果没有密码，这行可以删除或者留空
    database: 6

  rabbitmq:
    host: 192.168.72.128
    port: 5672
    username: bookTalk
    password: bookTalk
    virtualHost: /bookTalk

redisson:
  config: classpath:redisson.yml

  aop:
    auto: true

  elasticsearch:
    uris: 192.168.72.128:9200
    connection-timeout: 1s
    socket-timeout: 30s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



aliyun:
  oss:
    endpoint: ${ALIYUN_ENDPOINT}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: ${ALIYUN_BUCKET_NAME}


logging:
  level:
    root: info
    com.cc.talkadmin: debug



server:
  port: 8082
