spring:
  datasource:
    url: "jdbc:mysql://192.168.72.128:3306/book_talk?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}

  servlet:
    encoding:
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  redis:
    host: 192.168.72.128
    port: 6379
    password: ${REDIS_PASSWORD}   # 如果没有密码，这行可以删除或者留空
    database: 6


  rabbitmq:
    host: 192.168.72.128
    port: 5672
    username: bookTalk
    password: bookTalk
    virtual-host: /bookTalk

    # 添加这些配置
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

redisson:
  config: classpath:redisson.yml

  aop:
    auto: true

  elasticsearch:
    uris: 192.168.72.128:9200
    connection-timeout: 1s
    socket-timeout: 30s
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cc.talkpojo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cc.talkpojo.entity
  configuration:
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: ${ALIYUN_ENDPOINT}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: ${ALIYUN_BUCKET_NAME}


logging:
  level:
    root: info
    com.cc.talkadmin: debug
    com.cc.talkserver: debug
    com.cc.talkuser: debug
    org.springframework.amqp: DEBUG
    com.rabbitmq: DEBUG



server:
  port: 8081
