
spring:
  datasource:
    url: "jdbc:mysql://192.168.72.128:3306/book_talk?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}
  servlet:
    encoding:
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
  data:
    redis:
      port: 6379
      host: 192.168.72.128
      database: 6
      password: ${REDIS_PASSWORD}
  aop:
    auto: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher