

spring:
  datasource:
    url: "jdbc:mysql://192.168.72.128:3306/book_talk?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_PASSWORD}

  servlet:
    encoding:
      charset: UTF-8
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

  redis:
    port: 6379
    host: 192.168.72.128
    database: 6
    password: ${REDIS_PASSWORD}

  rabbitmq:
    host: 192.168.72.128
    port: 5672
    username: bookTalk
    password: bookTalk
    virtual-host: /bookTalk

    # 添加这些配置
    publisher-confirm-type: correlated
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3

  aop:
    auto: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher



aliyun:
  oss:
    endpoint: ${ALIYUN_ENDPOINT}
    access-key-id: ${ALIYUN_ACCESS_KEY_ID}
    access-key-secret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucket-name: ${ALIYUN_BUCKET_NAME}


logging:
  level:
    root: info
    com.cc.talkserver: debug
    com.cc.talkadmin: debug
    com.cc.talkuser: debug


server:
  port: 8081
